services:

  bot:
    build: .
    depends_on:
      - mongo
    env_file:
      - .env
    environment:
      - MPLCONFIGDIR=/bot/.state-save/matplotlib
    volumes:
      - ./.state-save:/bot/.state-save # Проброс каталога сохранения
      - ./logs:/bot/logs # Проброс каталога логов
      - ./bot/data:/bot/bot/data # Проброс каталога данных
      - ./config.json:/bot/config.json:ro # Проброс конфига
      - /etc/localtime:/etc/localtime:ro # Проброс времени
      - ./backups:/backups
      - ./fonts:/bot/fonts:ro # Проброс шрифтов
      - ./images:/bot/images:ro # Проброс изображений
    restart: unless-stopped
    networks:
      - shared_network

  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb:/data/db
    restart: always
    stop_signal: SIGINT
    networks:
      - shared_network

networks:
  shared_network:
    name: shared_network
    external: true
