@echo off
title DinoGochi Config Editor Starter
echo Starting DinoGochi Config Editor...
echo Starting Python Backend Server on http://localhost:5000/ ...
start "DinoGochi Config Backend" cmd /c "python server.py"
echo Starting Vite Frontend Server on http://localhost:5173/ ...
npm run dev
